name: Build Arkari

on: push

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            triplet: x64-windows-static
            artifact: windows-x64
          - os: ubuntu-latest
            triplet: x64-linux
            artifact: linux-x64
          - os: macos-13
            triplet: x64-osx
            artifact: mac-x64
          - os: macos-latest
            triplet: arm64-osx
            artifact: mac-arm64
    runs-on: ${{ matrix.os }}
    env:
      INSTALL_DIR: $RUNNER_TEMP/arkari-install
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: KomiMoe/Arkari
          path: arkari

      - name: Setup MSVC Developer Environment
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install prerequisites
        if: runner.os != 'Windows'
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y build-essential cmake ninja-build libxml2-dev liblzma-dev zlib1g-dev
          else
            brew update
            brew install cmake ninja libxml2 xz zlib
          fi

      - name: Cache build directory
        uses: actions/cache@v3
        with:
          path: build
          key: build-${{ matrix.os }}-${{ matrix.triplet }}-${{ hashFiles('arkari/llvm/**') }}
          restore-keys: |
            build-${{ matrix.os }}-${{ matrix.triplet }}-

      - name: Configure and build
        run: |
          mkdir -p build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DLLVM_ENABLE_PROJECTS="clang;lld;lldb" ../arkari/llvm
          ninja

      - name: Install
        run: |
          cd build
          ninja install

      - name: Archive artifact
        run: |
          cd "$INSTALL_DIR"
          tar -czf "${{ matrix.artifact }}.tar.gz" bin lib

      - uses: actions/upload-artifact@v4
        with:
          name: arkari-${{ matrix.artifact }}
          path: "${{ matrix.artifact }}.tar.gz"
